id: I41476D64
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T13:27:11+00:00'
last_modified: '2022-06-09T07:21:47.371428+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25858
  title: གྱི་ལིང་བཅུ་གསུམ་འབྱུང་ཁུངས་སྐོར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    7C4A:
      image_group_id: I1KG25860
      title: Volume 1 of gyi ling bcu gsum 'byung khungs skor/
      total_pages: 126
      order: 1
      base_file: 7C4A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
