id: P007909
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25858
  title: གྱི་ལིང་བཅུ་གསུམ་འབྱུང་ཁུངས་སྐོར།
  author: ''
  volumes:
    e2b8b0861f63447b9c3b8fbb8dfdd6af:
      image_group_id: I1KG25860
      title: ''
      volume_number: 1
      total_pages: 126
ebook_metadata:
  title: གྱི་ལིང་བཅུ་གསུམ་འབྱུང་ཁུངས་སྐོར།
  author: ''
  sku: P007909
  cover: cover.jpg
  layers:
  - pagination
